### ISSUE TITLE
Tags perdem o espaço

### ISSUE THREAD

**Issue by vanessa** [CITi-UFPE/citi-library#1]
Se você postar alguma coisa no library com tags com espaço ([planning poker](http://citi.org.br/library/learning/GJuaHRkT16ov3OJtS7x7), [marketing digital](http://citi.org.br/library/learning/eZbwKlwNXAYE0ldmP0lU), etc.) o script do próprio bot vai retirar o espaço, resultando em `PlanningPoker`, `MarketingDigital`, etc.

**Comment by amandasavluchinske** [comment]
@vanessa Acho que isso foi corrigido também

**Comment by vanessa** [comment]
@amandasavluchinske Não é visual, é na hora do bot parsear as tags mesmo. Quando você posta com a tag "planning poker" ele converte pra "planningpoker"

**Comment by amandasavluchinske** [comment]
Nani
