### ISSUE TITLE
Atualizar library do Firebase?

### ISSUE THREAD

**Issue by vanessa** [CITi-UFPE/citi-library#9]
Inicializar o bot com [essa opção](https://github.com/CITi-UFPE/citi-library/blob/master/bot/index.js#L29) está dando este erro:

>Unknown option 'timestampsInSnapshots' passed to function settings(). Available options: host, ssl, credentials

Talvez seja o mesmo problema reportado aqui https://github.com/FirebaseExtended/firebase-dart/issues/193

**Comment by amandasavluchinske** [comment]
@vanessa Será que ainda ta rolando? O projeto tá com firebase 5.5.0, o problema parece ter sido introduzido na 5.0.1. Tu sabe dizer?

**Comment by vanessa** [comment]
Foi corrigido mesmo, acabei de ver

**Comment by vanessa** [comment]
Pode fechar se tu puder

**Comment by amandasavluchinske** [comment]
Top
